### ISSUE TITLE
Unexpected jumps with clickToFocus and entering commands

### ISSUE THREAD

**Issue by GrandmasterGrogu** [rohanchandra/react-terminal-component#11]
_Environment_
Windows 7, Desktop, Chrome
Using a React Redux boilerplate

_Expected Behavior_
Clicking anywhere in the terminal will put focus into terminal, ready to type command.
Typing in commands will not cause the console to move.

_Actual Behavior_
It puts the focus into the terminal and scrolls down to it. The additional scroll behavior is not desirable.
Then, typing in commands causes the console to scroll down.

_Steps to reproduce_

1. Put a bunch of content before the terminal / console.
2. Put a bunch of content after the terminal.
3. Load page.
4. Click console. (Observe scrolling down here)
5. Type in commands. After entering each command, it will keep scrolling down the whole browser.

**Comment by GrandmasterGrogu** [comment]
When I played around with the code, I think I found a fix. If I have time, I'll look at it some more and make a pull request.
I'm thinking maybe a separate attribute for part of it. autoscroll?

**Comment by rohanchandra** [comment]
Thanks for the update, I would love to see a PR for this issue.

**Comment by GrandmasterGrogu** [comment]
Found this fix, there's two ways to implement...
One is to add false into scrollIntoView(), which causes it to scroll to the bottom of the terminal instead. This keeps the stuff above the terminal visible and the bottom of the terminal at the very bottom.
https://github.com/rohanchandra/react-terminal-component/blob/92eede895b218580d95637b15be082f07d995e42/src/input/CommandInput.js#L13

Alternatively, there can be a scrollToTop prop that goes to that function with default as false, though I am not sure if there is a situation where it is useful to keep it as scroll to top.

Completely removing the scroll does not exactly work because of the last line being partially obscured. There's probably a another way to fix it, but this way seems sufficient to me. 

Do you want a pull request with adding false or a whole new prop? I can do either.

**Comment by rohanchandra** [comment]
@alexxgathp Let's just pass in `false` for now (if there's an actual use-case for the prop we can always add it later).

**Comment by GrandmasterGrogu** [comment]
https://github.com/rohanchandra/react-terminal-component/pull/12

**Comment by GrandmasterGrogu** [comment]
Separated out the other thing
https://github.com/rohanchandra/react-terminal-component/pull/15

**Comment by rohanchandra** [comment]
Thanks for the updated PR, I've merged your changes from https://github.com/rohanchandra/react-terminal-component/pull/15 in.
