### ISSUE TITLE
yarn.lock and node version

### ISSUE THREAD

**Issue by GrandmasterGrogu** [rohanchandra/react-terminal-component#13]
Also, fyi I had to generate a new yarn.lock when using my version of node v10.15, due to some dependencies that worked differently after node 9.

**Comment by GrandmasterGrogu** [comment]
https://github.com/alexxgathp/react-terminal-component/commit/d4edf0350e7c28ffe2bd57e7529c36639c750be1

**Comment by rohanchandra** [comment]
I think we'll need to handle Node upgrades separately.

The scripts for building (`yarn build` and `yarn dev`) break with the pull request changes to `yarn.lock`, as it lands on a broken version of Webpack CLI: https://github.com/webpack/webpack-cli/issues/607

**Comment by rohanchandra** [comment]
Fixed in eea07dd089e45755994efea49bcb70169a84dfed
