### ISSUE TITLE
add new command ?

### ISSUE THREAD

**Issue by hosseinmh** [rohanchandra/react-terminal-component#2]
hi 
can you explain how to add some linux command such ass npm  or etc ?
is it possible ?
thanks

**Comment by rohanchandra** [comment]
Hi,

This component is useful for simulating a basic terminal environment in the web browser (potential use cases here https://github.com/rohanchandra/react-terminal-component#potential-uses) so, adding an entire package manager would be very complex.

Here's an example of the work required for a simple version of `rmdir`: https://github.com/rohanchandra/javascript-terminal/blob/master/src/commands/rmdir.js

For more information see the documentation available for adding commands at https://github.com/rohanchandra/javascript-terminal if you are interested.
